"""add discount and overhead to estimate model

Revision ID: 08e8981e867f
Revises: 23a7ed1f5d72
Create Date: 2025-12-25 17:59:07.129335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e8981e867f'
down_revision: Union[str, Sequence[str], None] = '23a7ed1f5d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Estimates', sa.Column('materials_overhead', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('Estimates', sa.Column('work_overhead', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('Estimates', sa.Column('materials_discount', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('Estimates', sa.Column('work_discount', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Estimates', 'work_discount')
    op.drop_column('Estimates', 'materials_discount')
    op.drop_column('Estimates', 'work_overhead')
    op.drop_column('Estimates', 'materials_overhead')
    # ### end Alembic commands ###
