"""Create Section table

Revision ID: 23a7ed1f5d72
Revises: 5ee9a94c4615
Create Date: 2025-12-14 16:41:04.903816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a7ed1f5d72'
down_revision: Union[str, Sequence[str], None] = '5ee9a94c4615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), server_default='', nullable=False),
    sa.Column('sort_index', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['Estimates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sort_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sections')
    # ### end Alembic commands ###
