"""disable sort index unique

Revision ID: 6dd658ee2b5c
Revises: 08e8981e867f
Create Date: 2025-12-28 16:20:31.327466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd658ee2b5c'
down_revision: Union[str, Sequence[str], None] = '08e8981e867f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Sections_sort_index_key'), 'Sections', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('Sections_sort_index_key'), 'Sections', ['sort_index'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
